package com.zc13.msmis.mapping;

/**
 * LimitCar generated by MyEclipse Persistence Tools
 */

public class LimitCar implements java.io.Serializable {

	// Fields

	private Integer id;
	private String beginDate;
	private String endDate;
	private String mon;
	private String tues;
	private String wed;
	private String thrus;
	private String friday;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public LimitCar() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public LimitCar(Integer id, String beginDate, String endDate, String mon, String tues, String wed, String thrus, String friday, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.mon = mon;
		this.tues = tues;
		this.wed = wed;
		this.thrus = thrus;
		this.friday = friday;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getMon() {
		return this.mon;
	}

	public void setMon(String mon) {
		this.mon = mon;
	}

	public String getTues() {
		return this.tues;
	}

	public void setTues(String tues) {
		this.tues = tues;
	}

	public String getWed() {
		return this.wed;
	}

	public void setWed(String wed) {
		this.wed = wed;
	}

	public String getThrus() {
		return this.thrus;
	}

	public void setThrus(String thrus) {
		this.thrus = thrus;
	}

	public String getFriday() {
		return this.friday;
	}

	public void setFriday(String friday) {
		this.friday = friday;
	}

}