package com.zc13.msmis.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MFunction generated by MyEclipse Persistence Tools
 */

public class MFunction implements java.io.Serializable {

	// Fields

	private Integer functionid;
	private String functionname;
	private String urlname;
	private String description;
	private String enabled;
	private Integer parentid;
	private Integer sequence;
	private Date updatetime;
	private Integer lpId;
	private Integer rootUser;
	private Set MRolePerms = new HashSet(0);

	// Constructors

	/** default constructor */
	public MFunction() {
	}

	/** minimal constructor */
	public MFunction(String functionname) {
		this.functionname = functionname;
	}

	// Property accessors

	public Integer getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(Integer functionid) {
		this.functionid = functionid;
	}

	public String getFunctionname() {
		return this.functionname;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public MFunction(Integer functionid, String functionname, String urlname, String description, String enabled, Integer parentid, Integer sequence, Date updatetime, Integer lpId, Integer rootUser, Set rolePerms) {
		super();
		this.functionid = functionid;
		this.functionname = functionname;
		this.urlname = urlname;
		this.description = description;
		this.enabled = enabled;
		this.parentid = parentid;
		this.sequence = sequence;
		this.updatetime = updatetime;
		this.lpId = lpId;
		this.rootUser = rootUser;
		MRolePerms = rolePerms;
	}

	public void setFunctionname(String functionname) {
		this.functionname = functionname;
	}

	public String getUrlname() {
		return this.urlname;
	}

	public void setUrlname(String urlname) {
		this.urlname = urlname;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Set getMRolePerms() {
		return this.MRolePerms;
	}

	public void setMRolePerms(Set MRolePerms) {
		this.MRolePerms = MRolePerms;
	}

}