package com.zc13.msmis.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MRole generated by MyEclipse Persistence Tools
 */

public class MRole implements java.io.Serializable {

	// Fields

	private Integer roleid;
	private String rolename;
	private String roledesc;
	private Integer enabled;
	private Date updatetime;
	private Integer range;
	private Integer lpId;
	private Integer rootUser;
	private Set MRolePerms = new HashSet(0);
	private Set MUserRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public MRole() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public MRole(Integer roleid, String rolename, String roledesc, Integer enabled, Date updatetime, Integer range, Integer lpId, Integer rootUser, Set rolePerms, Set userRoles) {
		super();
		this.roleid = roleid;
		this.rolename = rolename;
		this.roledesc = roledesc;
		this.enabled = enabled;
		this.updatetime = updatetime;
		this.range = range;
		this.lpId = lpId;
		this.rootUser = rootUser;
		MRolePerms = rolePerms;
		MUserRoles = userRoles;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRoledesc() {
		return this.roledesc;
	}

	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Set getMRolePerms() {
		return this.MRolePerms;
	}

	public void setMRolePerms(Set MRolePerms) {
		this.MRolePerms = MRolePerms;
	}

	public Set getMUserRoles() {
		return this.MUserRoles;
	}

	public void setMUserRoles(Set MUserRoles) {
		this.MUserRoles = MUserRoles;
	}

	public Integer getRange() {
		return range;
	}

	public void setRange(Integer range) {
		this.range = range;
	}

}