package com.zc13.msmis.mapping;

import java.util.Date;

/**
 * MRolePerm generated by MyEclipse Persistence Tools
 */

public class MRolePerm implements java.io.Serializable {

	// Fields

	private Integer relationid;
	private MRole MRole;
	private MFunction MFunction;
	private Date updatetime;
	private String description;
	private Integer enabled;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public MRolePerm() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public MRolePerm(Integer relationid, MRole role, MFunction function, Date updatetime, String description, Integer enabled, Integer lpId, Integer rootUser) {
		super();
		this.relationid = relationid;
		MRole = role;
		MFunction = function;
		this.updatetime = updatetime;
		this.description = description;
		this.enabled = enabled;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getRelationid() {
		return this.relationid;
	}

	public void setRelationid(Integer relationid) {
		this.relationid = relationid;
	}

	public MRole getMRole() {
		return this.MRole;
	}

	public void setMRole(MRole MRole) {
		this.MRole = MRole;
	}

	public MFunction getMFunction() {
		return this.MFunction;
	}

	public void setMFunction(MFunction MFunction) {
		this.MFunction = MFunction;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

}