package com.zc13.msmis.mapping;

/**
 * MUserRole generated by MyEclipse Persistence Tools
 */

public class MUserRole implements java.io.Serializable {

	// Fields

	private Integer relationid;
	private MUser MUser;
	private MRole MRole;
	private String description;
	private String enabled;
	private Integer lpId;
	private Integer rootUser;
	// Constructors

	/** default constructor */
	public MUserRole() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public MUserRole(Integer relationid, MUser user, MRole role, String description, String enabled, Integer lpId, Integer rootUser) {
		super();
		this.relationid = relationid;
		MUser = user;
		MRole = role;
		this.description = description;
		this.enabled = enabled;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getRelationid() {
		return this.relationid;
	}

	public void setRelationid(Integer relationid) {
		this.relationid = relationid;
	}

	public MUser getMUser() {
		return this.MUser;
	}

	public void setMUser(MUser MUser) {
		this.MUser = MUser;
	}

	public MRole getMRole() {
		return this.MRole;
	}

	public void setMRole(MRole MRole) {
		this.MRole = MRole;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}