package com.zc13.msmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * MUser generated by MyEclipse Persistence Tools
 */

public class MUser implements java.io.Serializable {

	// Fields

	private Integer userid;
	private String username;
	private String password;
	private String department;
	private String enabled;
	private String description;
	private String realName;
	private String phone;
	private String address;
	private String identityCard;
	private Integer lpId;
	private Integer rootUser;
	private Set MUserRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public MUser() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public MUser(Integer userid, String username, String password, String department, String enabled, String description, String realName, String phone, String address, String identityCard, Integer lpId, Integer rootUser, Set userRoles) {
		super();
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.department = department;
		this.enabled = enabled;
		this.description = description;
		this.realName = realName;
		this.phone = phone;
		this.address = address;
		this.identityCard = identityCard;
		this.lpId = lpId;
		this.rootUser = rootUser;
		MUserRoles = userRoles;
	}

	public Set getMUserRoles() {
		return this.MUserRoles;
	}

	public void setMUserRoles(Set MUserRoles) {
		this.MUserRoles = MUserRoles;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIdentityCard() {
		return identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

}