package com.zc13.msmis.mapping;

import java.util.Date;

/**
 * SysLog generated by MyEclipse Persistence Tools
 */

public class SysLog implements java.io.Serializable {

	// Fields

	private Integer id;
	private String operateType;
	private Integer operateUserId;
	private Date operateTime;
	private String operateUserName;
	private String operateContent;
	private String operateObj;
	private String operateModule;
	private Integer lpId;
	private Integer rootUser;
	// Constructors

	/** default constructor */
	public SysLog() {
	}

	// Property accessors

	public SysLog(Integer id, String operateType, Integer operateUserId, Date operateTime, String operateUserName, String operateContent, String operateObj, String operateModule, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.operateType = operateType;
		this.operateUserId = operateUserId;
		this.operateTime = operateTime;
		this.operateUserName = operateUserName;
		this.operateContent = operateContent;
		this.operateObj = operateObj;
		this.operateModule = operateModule;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public String getOperateObj() {
		return operateObj;
	}

	public void setOperateObj(String operateObj) {
		this.operateObj = operateObj;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOperateType() {
		return this.operateType;
	}

	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	public Integer getOperateUserId() {
		return this.operateUserId;
	}

	public void setOperateUserId(Integer operateUserId) {
		this.operateUserId = operateUserId;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getOperateContent() {
		return this.operateContent;
	}

	public void setOperateContent(String operateContent) {
		this.operateContent = operateContent;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getOperateUserName() {
		return operateUserName;
	}

	public void setOperateUserName(String operateUserName) {
		this.operateUserName = operateUserName;
	}

	public String getOperateModule() {
		return operateModule;
	}

	public void setOperateModule(String operateModule) {
		this.operateModule = operateModule;
	}

}