package com.zc13.bkmis.mapping;

/**
 * AnalysisCustomer generated by MyEclipse Persistence Tools
 */

public class AnalysisCustomer implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer lpId;
	private String createDate;
	private String beginDate;
	private String endDate;
	private Integer inamount;
	private Integer outamount;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public AnalysisCustomer() {
	}

	/** full constructor */
	public AnalysisCustomer(Integer lpId, String createDate, String beginDate,
			String endDate, Integer inamount, Integer outamount,
			Integer rootUser) {
		this.lpId = lpId;
		this.createDate = createDate;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.inamount = inamount;
		this.outamount = outamount;
		this.rootUser = rootUser;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLpId() {
		return this.lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Integer getInamount() {
		return this.inamount;
	}

	public void setInamount(Integer inamount) {
		this.inamount = inamount;
	}

	public Integer getOutamount() {
		return this.outamount;
	}

	public void setOutamount(Integer outamount) {
		this.outamount = outamount;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}