package com.zc13.bkmis.mapping;

/**
 * AnalysisClientComeGo generated by MyEclipse Persistence Tools
 */

public class AnalysisClientComeGo implements java.io.Serializable {

	// Fields

	private Integer id;
	private CompactClient compactClient;
	private ELp ELp;
	private String comeDate;
	private String goDate;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public AnalysisClientComeGo() {
	}

	/** full constructor */
	public AnalysisClientComeGo(CompactClient compactClient, ELp ELp,
			String comeDate, String goDate, Integer rootUser) {
		this.compactClient = compactClient;
		this.ELp = ELp;
		this.comeDate = comeDate;
		this.goDate = goDate;
		this.rootUser = rootUser;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CompactClient getCompactClient() {
		return this.compactClient;
	}

	public void setCompactClient(CompactClient compactClient) {
		this.compactClient = compactClient;
	}

	public ELp getELp() {
		return this.ELp;
	}

	public void setELp(ELp ELp) {
		this.ELp = ELp;
	}

	public String getComeDate() {
		return this.comeDate;
	}

	public void setComeDate(String comeDate) {
		this.comeDate = comeDate;
	}

	public String getGoDate() {
		return this.goDate;
	}

	public void setGoDate(String goDate) {
		this.goDate = goDate;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}