package com.zc13.bkmis.mapping;

/**
 * AnalysisCost generated by MyEclipse Persistence Tools
 */

public class AnalysisCost implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer lpId;
	private String createDate;
	private String beginDate;
	private String endDate;
	private float amountMoney;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public AnalysisCost() {
	}

	/** full constructor */
	public AnalysisCost(Integer lpId, String createDate, String beginDate,
			String endDate, float amountMoney, Integer rootUser) {
		this.lpId = lpId;
		this.createDate = createDate;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.amountMoney = amountMoney;
		this.rootUser = rootUser;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLpId() {
		return this.lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public float getAmountMoney() {
		return this.amountMoney;
	}

	public void setAmountMoney(float amountMoney) {
		this.amountMoney = amountMoney;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}