package com.zc13.bkmis.mapping;

/**
 * AwokeTaskRole generated by MyEclipse Persistence Tools
 */

public class AwokeTaskRole implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer taskId;
	private Integer roleId;
	private String description;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public AwokeTaskRole() {
	}

	public AwokeTaskRole(Integer id, Integer taskId, Integer roleId, String description, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.taskId = taskId;
		this.roleId = roleId;
		this.description = description;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

}