package com.zc13.bkmis.mapping;

/**
 * CCostparatype generated by MyEclipse Persistence Tools
 */

public class CCostparatype implements java.io.Serializable {

	// Fields

	private Integer id;
	private String typeCode;
	private String typeName;
	private String useGauge;
	private String code;
	private String codeType;
	private int totalcount;
	private Integer rootUser;
	private Integer lpId;
	//private Set<CCosttype> costTypes;
	// Constructors
	
	public CCostparatype(Integer id, String typeCode, String typeName, String useGauge, String code, String codeType, int totalcount, Integer rootUser, Integer lpId) {
		super();
		this.id = id;
		this.typeCode = typeCode;
		this.typeName = typeName;
		this.useGauge = useGauge;
		this.code = code;
		this.codeType = codeType;
		this.totalcount = totalcount;
		this.rootUser = rootUser;
		this.lpId = lpId;
	}

	/** default constructor */
	public CCostparatype() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getUseGauge() {
		return this.useGauge;
	}

	public void setUseGauge(String useGauge) {
		this.useGauge = useGauge;
	}


	public int getTotalcount() {
		return totalcount;
	}

	public void setTotalcount(int totalcount) {
		this.totalcount = totalcount;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeType() {
		return codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

//	public Set<CCosttype> getCostTypes() {
//		return costTypes;
//	}
//
//	public void setCostTypes(Set<CCosttype> costTypes) {
//		this.costTypes = costTypes;
//	}

}