package com.zc13.bkmis.mapping;

/**
 * CItems generated by MyEclipse Persistence Tools
 */

public class CItems implements java.io.Serializable {

	// Fields

	private Integer id;
	private String itemCode;
	private String itemName;
	private String countPaymentrate;
	private String explanation;
	private Integer indexs;
	private String value;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public CItems() {
	}

	// Property accessors

	public CItems(Integer id, String itemCode, String itemName, String countPaymentrate, String explanation, Integer indexs, String value, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.countPaymentrate = countPaymentrate;
		this.explanation = explanation;
		this.indexs = indexs;
		this.value = value;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getCountPaymentrate() {
		return this.countPaymentrate;
	}

	public void setCountPaymentrate(String countPaymentrate) {
		this.countPaymentrate = countPaymentrate;
	}

	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	public Integer getIndexs() {
		return this.indexs;
	}

	public void setIndexs(Integer indexs) {
		this.indexs = indexs;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}