package com.zc13.bkmis.mapping;

/**
 * CNotice generated by MyEclipse Persistence Tools
 */

public class CNotice implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer clientId;
	private String clientName;
	private Integer itemId;
	private Integer standardId;
	private String itemName;
	private String standardName;
	private double amount;
	private String billDate;
	private String closeDate;
	private Integer roomId;
	private String roomCode;
	private String noticeType;
	private String noticeDate;
	private String beginDate;
	private String endDate;
	private Integer lpId;
	private Integer rootUser;


	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public CNotice(Integer id, Integer clientId, String clientName, Integer itemId, Integer standardId, String itemName, String standardName, double amount, String billDate, String closeDate, Integer roomId, String roomCode, String noticeType, String noticeDate, String beginDate, String endDate, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.clientId = clientId;
		this.clientName = clientName;
		this.itemId = itemId;
		this.standardId = standardId;
		this.itemName = itemName;
		this.standardName = standardName;
		this.amount = amount;
		this.billDate = billDate;
		this.closeDate = closeDate;
		this.roomId = roomId;
		this.roomCode = roomCode;
		this.noticeType = noticeType;
		this.noticeDate = noticeDate;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	/** default constructor */
	public CNotice() {
	}

	/** full constructor */

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public Integer getStandardId() {
		return this.standardId;
	}

	public void setStandardId(Integer standardId) {
		this.standardId = standardId;
	}

	public String getStandardName() {
		return this.standardName;
	}

	public void setStandardName(String standardName) {
		this.standardName = standardName;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getBillDate() {
		return this.billDate;
	}

	public void setBillDate(String billDate) {
		this.billDate = billDate;
	}

	public String getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(String closeDate) {
		this.closeDate = closeDate;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public String getRoomCode() {
		return this.roomCode;
	}

	public void setRoomCode(String roomCode) {
		this.roomCode = roomCode;
	}

	public String getNoticeType() {
		return this.noticeType;
	}

	public void setNoticeType(String noticeType) {
		this.noticeType = noticeType;
	}

	public String getNoticeDate() {
		return this.noticeDate;
	}

	public void setNoticeDate(String noticeDate) {
		this.noticeDate = noticeDate;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Integer getItemId() {
		return itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

}