package com.zc13.bkmis.mapping;

/**
 * CompactRoom generated by MyEclipse Persistence Tools
 */

public class CompactRoom implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer pactId;
	private Integer roomId;
	private String description;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public CompactRoom() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public CompactRoom(Integer id, Integer pactId, Integer roomId, String description, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.pactId = pactId;
		this.roomId = roomId;
		this.description = description;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPactId() {
		return this.pactId;
	}

	public void setPactId(Integer pactId) {
		this.pactId = pactId;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}