package com.zc13.bkmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * CompactClient generated by MyEclipse Persistence Tools
 */

public class CompactClient implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String name;
	private String clientType;
	private String country;
	private String nation;
	private String residence;
	private String identityCard;
	private String linkMan;
	private String phone;
	private String unitName;
	private String companyType;
	private String trade;
	private String operation;
	private String fundType;
	private String corporation;
	private String fax;
	private String taxNo;
	private String rentNo;
	private String isHighTech;
	private String loginDate;
	private String loginFund;
	private Set EFloorMapCoordinates = new HashSet(0);
	private Set CBills = new HashSet(0);
	private Set analysisClientComeGos = new HashSet(0);
	private Set compactRoomCoststandards = new HashSet(0);
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public CompactClient() {
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public CompactClient(Integer id, String code, String name, String clientType, String country, String nation, String residence, String identityCard, String linkMan, String phone, String unitName, String companyType, String trade, String operation, String fundType, String corporation, String fax, String taxNo, String rentNo, String isHighTech, String loginDate, String loginFund, Set floorMapCoordinates, Set bills, Set analysisClientComeGos, Set compactRoomCoststandards, Integer lpId,
			Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.name = name;
		this.clientType = clientType;
		this.country = country;
		this.nation = nation;
		this.residence = residence;
		this.identityCard = identityCard;
		this.linkMan = linkMan;
		this.phone = phone;
		this.unitName = unitName;
		this.companyType = companyType;
		this.trade = trade;
		this.operation = operation;
		this.fundType = fundType;
		this.corporation = corporation;
		this.fax = fax;
		this.taxNo = taxNo;
		this.rentNo = rentNo;
		this.isHighTech = isHighTech;
		this.loginDate = loginDate;
		this.loginFund = loginFund;
		EFloorMapCoordinates = floorMapCoordinates;
		CBills = bills;
		this.analysisClientComeGos = analysisClientComeGos;
		this.compactRoomCoststandards = compactRoomCoststandards;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public String getRentNo() {
		return rentNo;
	}

	public void setRentNo(String rentNo) {
		this.rentNo = rentNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getResidence() {
		return this.residence;
	}

	public void setResidence(String residence) {
		this.residence = residence;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	public String getTrade() {
		return this.trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getIsHighTech() {
		return this.isHighTech;
	}

	public void setIsHighTech(String isHighTech) {
		this.isHighTech = isHighTech;
	}

	public String getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(String loginDate) {
		this.loginDate = loginDate;
	}

	public String getLoginFund() {
		return this.loginFund;
	}

	public void setLoginFund(String loginFund) {
		this.loginFund = loginFund;
	}

	public Set getEFloorMapCoordinates() {
		return this.EFloorMapCoordinates;
	}

	public void setEFloorMapCoordinates(Set EFloorMapCoordinates) {
		this.EFloorMapCoordinates = EFloorMapCoordinates;
	}

	public Set getCBills() {
		return this.CBills;
	}

	public void setCBills(Set CBills) {
		this.CBills = CBills;
	}

	public Set getAnalysisClientComeGos() {
		return this.analysisClientComeGos;
	}

	public void setAnalysisClientComeGos(Set analysisClientComeGos) {
		this.analysisClientComeGos = analysisClientComeGos;
	}

	public Set getCompactRoomCoststandards() {
		return this.compactRoomCoststandards;
	}

	public void setCompactRoomCoststandards(Set compactRoomCoststandards) {
		this.compactRoomCoststandards = compactRoomCoststandards;
	}

}