package com.zc13.bkmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * Compact generated by MyEclipse Persistence Tools
 */

public class Compact implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String type;
	private Integer clientId;
	private Integer intentionId;
	private String signDate;
	private String beginDate;
	private String endDate;
	private String goDate;
	private float totalArea;
	private String circle;
	private String roomCodes;
	private double rentDeposit;
	private String isRentDeposit;//是否已缴房租押金
	private double decorationDeposit;
	private String isDecorationDeposit;//是否已缴装修押金
	private String man;
	private String date;
	private String instruction;
	private String status;
	private String name;
	private String clientType;
	private String country;
	private String nation;
	private String residence;
	private String identityCard;
	private String linkMan;
	private String phone;
	private String unitName;
	private String companyType;
	private String trade;
	private String operation;
	private String fundType;
	private String corporation;
	private String fax;
	private String taxNo;
	private String rentNo;
	private String isHighTech;
	private String loginDate;
	private String loginFund;
	private float earnest;
	private String isEarnest;
	private String isDestine;
	private String inDate;
	private String isNotice;
	private Set compactRents = new HashSet(0);
	private Set compactChangesForNewId = new HashSet(0);
	private Set compactReletsForNewId = new HashSet(0);
	private Set CBills = new HashSet(0);
	private Set compactRoomCoststandards = new HashSet(0);
	private Set ERoomClients = new HashSet(0);
	private Set compactChangesForOldId = new HashSet(0);
	private Set compactReletsForOldId = new HashSet(0);
	private Set compactQuits = new HashSet(0);
	private Integer lpId;
	private Integer rootUser;

	public Compact(Integer id, String code, String type, Integer clientId, Integer intentionId, String signDate, String beginDate, String endDate, String goDate, float totalArea, String circle, String roomCodes, double rentDeposit, String isRentDeposit, double decorationDeposit, String isDecorationDeposit, String man, String date, String instruction, String status, String name, String clientType, String country, String nation, String residence, String identityCard, String linkMan, String phone,
			String unitName, String companyType, String trade, String operation, String fundType, String corporation, String fax, String taxNo, String rentNo, String isHighTech, String loginDate, String loginFund, float earnest, String isEarnest, String isDestine, String inDate, String isNotice, Set compactRents, Set compactChangesForNewId, Set compactReletsForNewId, Set bills, Set compactRoomCoststandards, Set roomClients, Set compactChangesForOldId, Set compactReletsForOldId,
			Set compactQuits, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.type = type;
		this.clientId = clientId;
		this.intentionId = intentionId;
		this.signDate = signDate;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.goDate = goDate;
		this.totalArea = totalArea;
		this.circle = circle;
		this.roomCodes = roomCodes;
		this.rentDeposit = rentDeposit;
		this.isRentDeposit = isRentDeposit;
		this.decorationDeposit = decorationDeposit;
		this.isDecorationDeposit = isDecorationDeposit;
		this.man = man;
		this.date = date;
		this.instruction = instruction;
		this.status = status;
		this.name = name;
		this.clientType = clientType;
		this.country = country;
		this.nation = nation;
		this.residence = residence;
		this.identityCard = identityCard;
		this.linkMan = linkMan;
		this.phone = phone;
		this.unitName = unitName;
		this.companyType = companyType;
		this.trade = trade;
		this.operation = operation;
		this.fundType = fundType;
		this.corporation = corporation;
		this.fax = fax;
		this.taxNo = taxNo;
		this.rentNo = rentNo;
		this.isHighTech = isHighTech;
		this.loginDate = loginDate;
		this.loginFund = loginFund;
		this.earnest = earnest;
		this.isEarnest = isEarnest;
		this.isDestine = isDestine;
		this.inDate = inDate;
		this.isNotice = isNotice;
		this.compactRents = compactRents;
		this.compactChangesForNewId = compactChangesForNewId;
		this.compactReletsForNewId = compactReletsForNewId;
		CBills = bills;
		this.compactRoomCoststandards = compactRoomCoststandards;
		ERoomClients = roomClients;
		this.compactChangesForOldId = compactChangesForOldId;
		this.compactReletsForOldId = compactReletsForOldId;
		this.compactQuits = compactQuits;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	/** default constructor */
	public Compact() {
	}

	public String getRentNo() {
		return rentNo;
	}

	public void setRentNo(String rentNo) {
		this.rentNo = rentNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public Integer getLpId() {
		return this.lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public String getSignDate() {
		return this.signDate;
	}

	public void setSignDate(String signDate) {
		this.signDate = signDate;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getGoDate() {
		return this.goDate;
	}

	public void setGoDate(String goDate) {
		this.goDate = goDate;
	}

	public float getTotalArea() {
		return this.totalArea;
	}

	public void setTotalArea(float totalArea) {
		this.totalArea = totalArea;
	}

	public String getCircle() {
		return this.circle;
	}

	public void setCircle(String circle) {
		this.circle = circle;
	}

	public String getRoomCodes() {
		return this.roomCodes;
	}

	public void setRoomCodes(String roomCodes) {
		this.roomCodes = roomCodes;
	}

	public double getRentDeposit() {
		return rentDeposit;
	}

	public void setRentDeposit(double rentDeposit) {
		this.rentDeposit = rentDeposit;
	}

	public double getDecorationDeposit() {
		return decorationDeposit;
	}


	public void setDecorationDeposit(double decorationDeposit) {
		this.decorationDeposit = decorationDeposit;
	}


	public String getMan() {
		return this.man;
	}

	public void setMan(String man) {
		this.man = man;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getResidence() {
		return this.residence;
	}

	public void setResidence(String residence) {
		this.residence = residence;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	public String getTrade() {
		return this.trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	public String getIsHighTech() {
		return this.isHighTech;
	}

	public void setIsHighTech(String isHighTech) {
		this.isHighTech = isHighTech;
	}

	public String getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(String loginDate) {
		this.loginDate = loginDate;
	}

	public String getLoginFund() {
		return this.loginFund;
	}

	public void setLoginFund(String loginFund) {
		this.loginFund = loginFund;
	}

	public float getEarnest() {
		return this.earnest;
	}

	public void setEarnest(float earnest) {
		this.earnest = earnest;
	}

	public String getIsEarnest() {
		return this.isEarnest;
	}


	/**
	 * 是否已缴定金
	 * Compact.setIsDestine
	 */
	public void setIsEarnest(String isEarnest) {
		this.isEarnest = isEarnest;
	}

	public String getIsDestine() {
		return this.isDestine;
	}

	/**
	 * 合同状态。常规，预租，过期
	 * Compact.getInDate
	 */
	public void setIsDestine(String isDestine) {
		this.isDestine = isDestine;
	}
	public String getInDate() {
		return this.inDate;
	}

	public void setInDate(String inDate) {
		this.inDate = inDate;
	}
	public String getIsNotice() {
		return this.isNotice;
	}

	/**
	 * 入驻状态，未通知，已通知，……已迁出
	 * Compact.getIsNotice
	 */
	public void setIsNotice(String isNotice) {
		this.isNotice = isNotice;
	}

	public Set getCompactRents() {
		return this.compactRents;
	}

	public void setCompactRents(Set compactRents) {
		this.compactRents = compactRents;
	}

	public Set getCompactChangesForNewId() {
		return this.compactChangesForNewId;
	}

	public void setCompactChangesForNewId(Set compactChangesForNewId) {
		this.compactChangesForNewId = compactChangesForNewId;
	}

	public Set getCompactReletsForNewId() {
		return this.compactReletsForNewId;
	}

	public void setCompactReletsForNewId(Set compactReletsForNewId) {
		this.compactReletsForNewId = compactReletsForNewId;
	}

	public Set getCBills() {
		return this.CBills;
	}

	public void setCBills(Set CBills) {
		this.CBills = CBills;
	}

	public Set getCompactRoomCoststandards() {
		return this.compactRoomCoststandards;
	}

	public void setCompactRoomCoststandards(Set compactRoomCoststandards) {
		this.compactRoomCoststandards = compactRoomCoststandards;
	}

	public Set getERoomClients() {
		return this.ERoomClients;
	}

	public void setERoomClients(Set ERoomClients) {
		this.ERoomClients = ERoomClients;
	}

	public Set getCompactChangesForOldId() {
		return this.compactChangesForOldId;
	}

	public void setCompactChangesForOldId(Set compactChangesForOldId) {
		this.compactChangesForOldId = compactChangesForOldId;
	}

	public Set getCompactReletsForOldId() {
		return this.compactReletsForOldId;
	}

	public void setCompactReletsForOldId(Set compactReletsForOldId) {
		this.compactReletsForOldId = compactReletsForOldId;
	}

	public Set getCompactQuits() {
		return this.compactQuits;
	}

	public void setCompactQuits(Set compactQuits) {
		this.compactQuits = compactQuits;
	}

	public Integer getIntentionId() {
		return intentionId;
	}

	public void setIntentionId(Integer intentionId) {
		this.intentionId = intentionId;
	}

	public String getIsRentDeposit() {
		return isRentDeposit;
	}

	public void setIsRentDeposit(String isRentDeposit) {
		this.isRentDeposit = isRentDeposit;
	}

	public String getIsDecorationDeposit() {
		return isDecorationDeposit;
	}

	public void setIsDecorationDeposit(String isDecorationDeposit) {
		this.isDecorationDeposit = isDecorationDeposit;
	}

}