package com.zc13.bkmis.mapping;

/**
 * 合同续租表
 * CompactRelet generated by MyEclipse Persistence Tools
 */

public class CompactRelet implements java.io.Serializable {

	// Fields

	private Integer id;
	private Compact compactByNewId;
	private Compact compactByOldId;
	private String oldCode;
	private String newCode;
	private String clientName;
	private String applyDate;
	private String theMan;
	private String status;
	private String bz;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public CompactRelet() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compact getCompactByNewId() {
		return this.compactByNewId;
	}

	public void setCompactByNewId(Compact compactByNewId) {
		this.compactByNewId = compactByNewId;
	}

	public Compact getCompactByOldId() {
		return this.compactByOldId;
	}

	public void setCompactByOldId(Compact compactByOldId) {
		this.compactByOldId = compactByOldId;
	}

	public String getOldCode() {
		return this.oldCode;
	}

	public void setOldCode(String oldCode) {
		this.oldCode = oldCode;
	}

	public String getNewCode() {
		return this.newCode;
	}

	public void setNewCode(String newCode) {
		this.newCode = newCode;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(String applyDate) {
		this.applyDate = applyDate;
	}

	public String getTheMan() {
		return this.theMan;
	}

	public void setTheMan(String theMan) {
		this.theMan = theMan;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public CompactRelet(Integer id, Compact compactByNewId, Compact compactByOldId, String oldCode, String newCode, String clientName, String applyDate, String theMan, String status, String bz, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.compactByNewId = compactByNewId;
		this.compactByOldId = compactByOldId;
		this.oldCode = oldCode;
		this.newCode = newCode;
		this.clientName = clientName;
		this.applyDate = applyDate;
		this.theMan = theMan;
		this.status = status;
		this.bz = bz;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

}