package com.zc13.bkmis.mapping;

/**
 * CompactTask generated by MyEclipse Persistence Tools
 */

public class CompactTask implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String clientName;
	private String rooms;
	private Integer compactId;
	private String compactCode;
	private String linkMan;
	private String linkPhone;
	private String inDate;
	private String goDate;
	private Integer phones;
	private String internets;
	private Integer keys;
	private String zhaos;
	private String caiwu;
	private String wuye;
	private String gongc;
	private String noteDate;
	private Integer lpId;
	private Integer rootUser;

	private int totalcount;
	// Constructors

	/** default constructor */
	public CompactTask() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public CompactTask(Integer id, String code, String clientName, String rooms, Integer compactId, String compactCode, String linkMan, String linkPhone, String inDate, String goDate, Integer phones, String internets, Integer keys, String zhaos, String caiwu, String wuye, String noteDate, Integer lpId, Integer rootUser, int totalcount) {
		super();
		this.id = id;
		this.code = code;
		this.clientName = clientName;
		this.rooms = rooms;
		this.compactId = compactId;
		this.compactCode = compactCode;
		this.linkMan = linkMan;
		this.linkPhone = linkPhone;
		this.inDate = inDate;
		this.goDate = goDate;
		this.phones = phones;
		this.internets = internets;
		this.keys = keys;
		this.zhaos = zhaos;
		this.caiwu = caiwu;
		this.wuye = wuye;
		this.noteDate = noteDate;
		this.lpId = lpId;
		this.rootUser = rootUser;
		this.totalcount = totalcount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getRooms() {
		return this.rooms;
	}

	public void setRooms(String rooms) {
		this.rooms = rooms;
	}

	public Integer getCompactId() {
		return this.compactId;
	}

	public void setCompactId(Integer compactId) {
		this.compactId = compactId;
	}

	public String getCompactCode() {
		return this.compactCode;
	}

	public void setCompactCode(String compactCode) {
		this.compactCode = compactCode;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getLinkPhone() {
		return this.linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getInDate() {
		return this.inDate;
	}

	public void setInDate(String inDate) {
		this.inDate = inDate;
	}

	public String getGoDate() {
		return this.goDate;
	}

	public void setGoDate(String goDate) {
		this.goDate = goDate;
	}

	public Integer getPhones() {
		return this.phones;
	}

	public void setPhones(Integer phones) {
		this.phones = phones;
	}

	public String getInternets() {
		return this.internets;
	}

	public void setInternets(String internets) {
		this.internets = internets;
	}

	public Integer getKeys() {
		return this.keys;
	}

	public void setKeys(Integer keys) {
		this.keys = keys;
	}

	public String getZhaos() {
		return this.zhaos;
	}

	public void setZhaos(String zhaos) {
		this.zhaos = zhaos;
	}

	public String getCaiwu() {
		return this.caiwu;
	}

	public void setCaiwu(String caiwu) {
		this.caiwu = caiwu;
	}

	public String getWuye() {
		return this.wuye;
	}

	public void setWuye(String wuye) {
		this.wuye = wuye;
	}

	public int getTotalcount() {
		return totalcount;
	}

	public void setTotalcount(int totalcount) {
		this.totalcount = totalcount;
	}

	public String getNoteDate() {
		return noteDate;
	}

	public void setNoteDate(String noteDate) {
		this.noteDate = noteDate;
	}

	public String getGongc() {
		return gongc;
	}

	public void setGongc(String gongc) {
		this.gongc = gongc;
	}

}