package com.zc13.bkmis.mapping;

/**
 * CompactRent generated by MyEclipse Persistence Tools
 */

public class CompactRent implements java.io.Serializable {

	// Fields

	private Integer id;
	private Compact compact;
	private double rent;
	private String beginDate;
	private String endDate;
	private String status;
	private Integer lpId;
	private Integer rootUser;

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public CompactRent(Integer id, Compact compact, double rent, String beginDate, String endDate, String status, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.compact = compact;
		this.rent = rent;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.status = status;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	/** default constructor */
	public CompactRent() {
	}

	/** full constructor */
	

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compact getCompact() {
		return this.compact;
	}

	public void setCompact(Compact compact) {
		this.compact = compact;
	}

	public double getRent() {
		return rent;
	}

	public void setRent(double rent) {
		this.rent = rent;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}