package com.zc13.bkmis.mapping;

/**
 * CompactRoomCoststandard generated by MyEclipse Persistence Tools
 */

public class CompactRoomCoststandard implements java.io.Serializable {

	// Fields

	private Integer id;
	private CCoststandard CCoststandard;
	private CompactClient compactClient;
	private ERooms ERooms;
	private CCosttype CCosttype;
	private Compact compact;
	private String beginDate;
	private String endDate;
	private String lastBuildDate;
	private String rebate;
	private Integer amount;
	private String status;
	private String display;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public CompactRoomCoststandard() {
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CCoststandard getCCoststandard() {
		return this.CCoststandard;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public CompactRoomCoststandard(Integer id, CCoststandard coststandard, CompactClient compactClient, ERooms rooms, CCosttype costtype, Compact compact, String beginDate, String endDate, String lastBuildDate, String rebate, Integer amount, String status, String display, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		CCoststandard = coststandard;
		this.compactClient = compactClient;
		ERooms = rooms;
		CCosttype = costtype;
		this.compact = compact;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.lastBuildDate = lastBuildDate;
		this.rebate = rebate;
		this.amount = amount;
		this.status = status;
		this.display = display;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public void setCCoststandard(CCoststandard CCoststandard) {
		this.CCoststandard = CCoststandard;
	}

	public CompactClient getCompactClient() {
		return this.compactClient;
	}

	public void setCompactClient(CompactClient compactClient) {
		this.compactClient = compactClient;
	}

	public ERooms getERooms() {
		return this.ERooms;
	}

	public void setERooms(ERooms ERooms) {
		this.ERooms = ERooms;
	}

	public CCosttype getCCosttype() {
		return this.CCosttype;
	}

	public void setCCosttype(CCosttype CCosttype) {
		this.CCosttype = CCosttype;
	}

	public Compact getCompact() {
		return this.compact;
	}

	public void setCompact(Compact compact) {
		this.compact = compact;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getRebate() {
		return this.rebate;
	}

	public void setRebate(String rebate) {
		this.rebate = rebate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getLastBuildDate() {
		return lastBuildDate;
	}

	public void setLastBuildDate(String lastBuildDate) {
		this.lastBuildDate = lastBuildDate;
	}

	public String getDisplay() {
		return display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

}