package com.zc13.bkmis.mapping;

/**
 * CompactQuit generated by MyEclipse Persistence Tools
 */

public class CompactQuit implements java.io.Serializable {

	// Fields

	private Integer id;
	private Compact compact;
	private String quitCode;
	private String applayDate;
	private String clientName;
	private String quitDate;
	private String quitSeason;
	private String validate;
	private String bz;
	private String doMan;
	private String zsbAttitude;
	private String cwbAttitude;
	private String wybAttitude;
	private String zjlAttitude;
	private String status;
	private Integer lpId;
	private Integer rootUser;
	//120928新加字段
	private String kfbAttitude;//客服部意见
	private String gcbAttitude;//工程部意见

	// Constructors

	public String getKfbAttitude() {
		return kfbAttitude;
	}

	public void setKfbAttitude(String kfbAttitude) {
		this.kfbAttitude = kfbAttitude;
	}

	public String getGcbAttitude() {
		return gcbAttitude;
	}

	public void setGcbAttitude(String gcbAttitude) {
		this.gcbAttitude = gcbAttitude;
	}

	/** default constructor */
	public CompactQuit() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public CompactQuit(Integer id, Compact compact, String quitCode, String applayDate, String clientName, String quitDate, String quitSeason, String validate, String bz, String doMan, String zsbAttitude, String cwbAttitude, String wybAttitude, String zjlAttitude, String status, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.compact = compact;
		this.quitCode = quitCode;
		this.applayDate = applayDate;
		this.clientName = clientName;
		this.quitDate = quitDate;
		this.quitSeason = quitSeason;
		this.validate = validate;
		this.bz = bz;
		this.doMan = doMan;
		this.zsbAttitude = zsbAttitude;
		this.cwbAttitude = cwbAttitude;
		this.wybAttitude = wybAttitude;
		this.zjlAttitude = zjlAttitude;
		this.status = status;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compact getCompact() {
		return this.compact;
	}

	public void setCompact(Compact compact) {
		this.compact = compact;
	}

	public String getQuitCode() {
		return this.quitCode;
	}

	public void setQuitCode(String quitCode) {
		this.quitCode = quitCode;
	}

	public String getApplayDate() {
		return this.applayDate;
	}

	public void setApplayDate(String applayDate) {
		this.applayDate = applayDate;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getQuitDate() {
		return this.quitDate;
	}

	public void setQuitDate(String quitDate) {
		this.quitDate = quitDate;
	}

	public String getQuitSeason() {
		return this.quitSeason;
	}

	public void setQuitSeason(String quitSeason) {
		this.quitSeason = quitSeason;
	}

	public String getValidate() {
		return this.validate;
	}

	public void setValidate(String validate) {
		this.validate = validate;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getDoMan() {
		return this.doMan;
	}

	public void setDoMan(String doMan) {
		this.doMan = doMan;
	}

	public String getZsbAttitude() {
		return this.zsbAttitude;
	}

	public void setZsbAttitude(String zsbAttitude) {
		this.zsbAttitude = zsbAttitude;
	}

	public String getCwbAttitude() {
		return this.cwbAttitude;
	}

	public void setCwbAttitude(String cwbAttitude) {
		this.cwbAttitude = cwbAttitude;
	}

	public String getWybAttitude() {
		return this.wybAttitude;
	}

	public void setWybAttitude(String wybAttitude) {
		this.wybAttitude = wybAttitude;
	}

	public String getZjlAttitude() {
		return this.zjlAttitude;
	}

	public void setZjlAttitude(String zjlAttitude) {
		this.zjlAttitude = zjlAttitude;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}