package com.zc13.bkmis.mapping;

/**
 * DepotInOutputList generated by MyEclipse Persistence Tools
 */

public class DepotInOutputList implements java.io.Serializable {

	// Fields

	private Integer id;
	private String inOutputCode;
	private Integer materialId;
	private double amount;
	private double unitPrice;
	private double amountMoney;
	private String type2;
	private String date;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotInOutputList() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public DepotInOutputList(Integer id, String inOutputCode,
			Integer materialId, double amount, double unitPrice,
			double amountMoney, String type2, String date, Integer lpId,
			Integer rootUser) {
		super();
		this.id = id;
		this.inOutputCode = inOutputCode;
		this.materialId = materialId;
		this.amount = amount;
		this.unitPrice = unitPrice;
		this.amountMoney = amountMoney;
		this.type2 = type2;
		this.date = date;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getInOutputCode() {
		return inOutputCode;
	}

	public void setInOutputCode(String inOutputCode) {
		this.inOutputCode = inOutputCode;
	}

	public Integer getMaterialId() {
		return materialId;
	}

	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public double getAmountMoney() {
		return amountMoney;
	}

	public void setAmountMoney(double amountMoney) {
		this.amountMoney = amountMoney;
	}

	public String getType2() {
		return type2;
	}

	public void setType2(String type2) {
		this.type2 = type2;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}