package com.zc13.bkmis.mapping;

/**
 * DepotMaterial generated by MyEclipse Persistence Tools
 */

public class DepotMaterial implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String name;
	private String type;
	private String spec;
	private String unit;
	private double lowerLimit;
	private double upperLimit;
	private double nowStock;
	private double money;
	private double doStock;
	private double unitPrice;
	private String bz;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotMaterial() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public DepotMaterial(Integer id, String code, String name, String type,
			String spec, String unit, double lowerLimit, double upperLimit,
			double nowStock, double money, double doStock, double unitPrice,
			String bz, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.name = name;
		this.type = type;
		this.spec = spec;
		this.unit = unit;
		this.lowerLimit = lowerLimit;
		this.upperLimit = upperLimit;
		this.nowStock = nowStock;
		this.money = money;
		this.doStock = doStock;
		this.unitPrice = unitPrice;
		this.bz = bz;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSpec() {
		return spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public double getLowerLimit() {
		return lowerLimit;
	}

	public void setLowerLimit(double lowerLimit) {
		this.lowerLimit = lowerLimit;
	}

	public double getUpperLimit() {
		return upperLimit;
	}

	public void setUpperLimit(double upperLimit) {
		this.upperLimit = upperLimit;
	}

	public double getNowStock() {
		return nowStock;
	}

	public void setNowStock(double nowStock) {
		this.nowStock = nowStock;
	}

	public double getMoney() {
		return money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public double getDoStock() {
		return doStock;
	}

	public void setDoStock(double doStock) {
		this.doStock = doStock;
	}

	public double getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}