package com.zc13.bkmis.mapping;

/**
 * DepotSupplier generated by MyEclipse Persistence Tools
 */

public class DepotSupplier implements java.io.Serializable {

	// Fields

	private Integer id;
	private String name;
	private String fullName;
	private String linkMan;
	private String phone;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotSupplier() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public DepotSupplier(Integer id, String name, String fullName, String linkMan, String phone, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.name = name;
		this.fullName = fullName;
		this.linkMan = linkMan;
		this.phone = phone;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}