package com.zc13.bkmis.mapping;

/**
 * DepotMaterialType generated by MyEclipse Persistence Tools
 */

public class DepotMaterialType implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String name;
	private String description;
	private Integer parentid;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotMaterialType() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public DepotMaterialType(Integer id, String code, String name, String description, Integer parentid, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.name = name;
		this.description = description;
		this.parentid = parentid;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}