package com.zc13.bkmis.mapping;

/**
 * DepotOutputManager generated by MyEclipse Persistence Tools
 */

public class DepotOutputManager implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String date;
	private String type2;
	private String man;
	private String department;
	private double money;
	private String status;
	private String updateDate;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotOutputManager() {
	}

	// Property accessors
	public DepotOutputManager(Integer id, String code, String date,
			String type2, String man, String department, double money,
			String status, String updateDate, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.date = date;
		this.type2 = type2;
		this.man = man;
		this.department = department;
		this.money = money;
		this.status = status;
		this.updateDate = updateDate;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getType2() {
		return type2;
	}

	public void setType2(String type2) {
		this.type2 = type2;
	}

	public String getMan() {
		return man;
	}

	public void setMan(String man) {
		this.man = man;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public double getMoney() {
		return money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}