package com.zc13.bkmis.mapping;

/**
 * DepotAdjustAccounts generated by MyEclipse Persistence Tools
 */

public class DepotAdjustAccounts implements java.io.Serializable {

	// Fields

	private Integer id;
	private String makeDate;
	private String year;
	private String month;
	private String beginDate;
	private String endDate;
	private double beginAmount;//期初数量
	private double beginMoney;//期初金额
	private double inputAccount;//本期入库数量
	private double inputMomey;//本期入库金额
	private double outputAccount;//本期出库数量
	private double outputMoney;//本期出库金额
	private double residue;//库存数量
	private double balance;//库存金额
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public DepotAdjustAccounts(Integer id, String makeDate, String year,
			String month, String beginDate, String endDate, double beginAmount,
			double beginMoney, double inputAccount, double inputMomey,
			double outputAccount, double outputMoney, double residue,
			double balance, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.makeDate = makeDate;
		this.year = year;
		this.month = month;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.beginAmount = beginAmount;
		this.beginMoney = beginMoney;
		this.inputAccount = inputAccount;
		this.inputMomey = inputMomey;
		this.outputAccount = outputAccount;
		this.outputMoney = outputMoney;
		this.residue = residue;
		this.balance = balance;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	/** default constructor */
	public DepotAdjustAccounts() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMakeDate() {
		return makeDate;
	}

	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public double getBeginAmount() {
		return beginAmount;
	}

	public void setBeginAmount(double beginAmount) {
		this.beginAmount = beginAmount;
	}

	public double getBeginMoney() {
		return beginMoney;
	}

	public void setBeginMoney(double beginMoney) {
		this.beginMoney = beginMoney;
	}

	public double getInputAccount() {
		return inputAccount;
	}

	public void setInputAccount(double inputAccount) {
		this.inputAccount = inputAccount;
	}

	public double getInputMomey() {
		return inputMomey;
	}

	public void setInputMomey(double inputMomey) {
		this.inputMomey = inputMomey;
	}

	public double getOutputAccount() {
		return outputAccount;
	}

	public void setOutputAccount(double outputAccount) {
		this.outputAccount = outputAccount;
	}

	public double getOutputMoney() {
		return outputMoney;
	}

	public void setOutputMoney(double outputMoney) {
		this.outputMoney = outputMoney;
	}

	public double getResidue() {
		return residue;
	}

	public void setResidue(double residue) {
		this.residue = residue;
	}

	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}