package com.zc13.bkmis.mapping;

/**
 * DepotInputManager generated by MyEclipse Persistence Tools
 */

public class DepotInputManager implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String date;
	private String type2;
	private String man;
	private double money;
	private String invoiceCode;
	private String supplierId;
	private String status;
	private String updateDate;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public DepotInputManager() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public DepotInputManager(Integer id, String code, String date,
			String type2, String man, double money, String invoiceCode,
			String supplierId, String status, String updateDate, Integer lpId,
			Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.date = date;
		this.type2 = type2;
		this.man = man;
		this.money = money;
		this.invoiceCode = invoiceCode;
		this.supplierId = supplierId;
		this.status = status;
		this.updateDate = updateDate;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getType2() {
		return this.type2;
	}

	public void setType2(String type2) {
		this.type2 = type2;
	}

	public String getMan() {
		return this.man;
	}

	public void setMan(String man) {
		this.man = man;
	}

	public double getMoney() {
		return money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public String getInvoiceCode() {
		return this.invoiceCode;
	}

	public void setInvoiceCode(String invoiceCode) {
		this.invoiceCode = invoiceCode;
	}

	public String getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}