package com.zc13.bkmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * EBuilds generated by MyEclipse Persistence Tools
 */

public class EBuilds implements java.io.Serializable {

	// Fields

	private Integer buildId;
	private ELp ELp;
	private String buildCode;
	private String buildName;
	private float useArea;
	private String floor;
	private String block;
	private String purpose;
	private String structure;
	private String beginDate;
	private String endDate;
	private Integer indexs;
	private Integer rootUser;
	/**
	 * hxj
	 *  楼栋平面图的存取器 */
	private String mapUrl;
	private Set ERoomses = new HashSet(0);

	// Constructors

	/** default constructor */
	public EBuilds() {
	}

	public EBuilds(Integer buildId) {
		super();
		this.buildId = buildId;
	}

	/** full constructor */
	public EBuilds(ELp ELp, String buildCode, String buildName, float useArea,
			String floor, String block, String purpose, String structure,
			String beginDate, String endDate, Integer indexs, Integer rootUser,
			String mapUrl, Set ERoomses) {
		this.ELp = ELp;
		this.buildCode = buildCode;
		this.buildName = buildName;
		this.useArea = useArea;
		this.floor = floor;
		this.block = block;
		this.purpose = purpose;
		this.structure = structure;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.indexs = indexs;
		this.rootUser = rootUser;
		this.mapUrl = mapUrl;
		this.ERoomses = ERoomses;
	}

	// Property accessors

	public Integer getBuildId() {
		return this.buildId;
	}

	public void setBuildId(Integer buildId) {
		this.buildId = buildId;
	}

	public ELp getELp() {
		return this.ELp;
	}

	public void setELp(ELp ELp) {
		this.ELp = ELp;
	}

	public String getBuildCode() {
		return this.buildCode;
	}

	public void setBuildCode(String buildCode) {
		this.buildCode = buildCode;
	}

	public String getBuildName() {
		return this.buildName;
	}

	public void setBuildName(String buildName) {
		this.buildName = buildName;
	}

	public float getUseArea() {
		return this.useArea;
	}

	public void setUseArea(float useArea) {
		this.useArea = useArea;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	public String getPurpose() {
		return purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getStructure() {
		return this.structure;
	}

	public void setStructure(String structure) {
		this.structure = structure;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Integer getIndexs() {
		return this.indexs;
	}

	public void setIndexs(Integer indexs) {
		this.indexs = indexs;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public Set getERoomses() {
		return this.ERoomses;
	}

	public void setERoomses(Set ERoomses) {
		this.ERoomses = ERoomses;
	}

	/**
	 * hxj
	 * 楼栋平面图的存取器
	 * @return
	 */
	public String getMapUrl() {
		return mapUrl;
	}

	public void setMapUrl(String mapUrl) {
		this.mapUrl = mapUrl;
	}
	

}