package com.zc13.bkmis.mapping;

/**
 * EFloorMapCoordinate generated by MyEclipse Persistence Tools
 */

public class EFloorMapCoordinate implements java.io.Serializable {

	// Fields

	private Integer id;
	private CompactClient compactClient;
	private EFloorMap EFloorMap;
	private Integer roomId;
	private double XCoordinate;
	private double YCoordinate;
	private double mapWidth;
	private String status;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public EFloorMapCoordinate() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public EFloorMapCoordinate(Integer id, CompactClient compactClient, EFloorMap floorMap, Integer roomId, double coordinate, double coordinate2, double mapWidth, String status, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.compactClient = compactClient;
		EFloorMap = floorMap;
		this.roomId = roomId;
		XCoordinate = coordinate;
		YCoordinate = coordinate2;
		this.mapWidth = mapWidth;
		this.status = status;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CompactClient getCompactClient() {
		return this.compactClient;
	}

	public void setCompactClient(CompactClient compactClient) {
		this.compactClient = compactClient;
	}

	public EFloorMap getEFloorMap() {
		return this.EFloorMap;
	}

	public void setEFloorMap(EFloorMap EFloorMap) {
		this.EFloorMap = EFloorMap;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public double getXCoordinate() {
		return this.XCoordinate;
	}

	public void setXCoordinate(double XCoordinate) {
		this.XCoordinate = XCoordinate;
	}

	public double getYCoordinate() {
		return this.YCoordinate;
	}

	public void setYCoordinate(double YCoordinate) {
		this.YCoordinate = YCoordinate;
	}

	public double getMapWidth() {
		return this.mapWidth;
	}

	public void setMapWidth(double mapWidth) {
		this.mapWidth = mapWidth;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}