package com.zc13.bkmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * ELp generated by MyEclipse Persistence Tools
 */

public class ELp implements java.io.Serializable {

	// Fields

	private Integer lpId;
	private String lpCode;
	private String lpName;
	private String regional;
	private String developCompany;
	private String designCompany;
	private String buildCompany;
	private float constructionArea;
	private float useArea;
	private float virescenceArea;
	private String beginDate;
	private String endDate;
	private String useDate;
	private String phone;
	private String fax;
	private String mapUrl;
	private String address;
	private Integer rootUser;
	private String ppType;
	private Set EBuildses = new HashSet(0);
	private Set analysisClientComeGos = new HashSet(0);

	// Constructors

	/** default constructor */
	public ELp() {
	}
	
	public ELp(Integer lpId) {
		super();
		this.lpId = lpId;
	}

	/** full constructor */
	public ELp(String lpCode, String lpName, String regional,
			String developCompany, String designCompany, String buildCompany,
			float constructionArea, float useArea, float virescenceArea,
			String beginDate, String endDate, String useDate, String phone,
			String fax, String mapUrl, String address, Integer rootUser,
			String ppType, Set EBuildses, Set analysisClientComeGos) {
		this.lpCode = lpCode;
		this.lpName = lpName;
		this.regional = regional;
		this.developCompany = developCompany;
		this.designCompany = designCompany;
		this.buildCompany = buildCompany;
		this.constructionArea = constructionArea;
		this.useArea = useArea;
		this.virescenceArea = virescenceArea;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.useDate = useDate;
		this.phone = phone;
		this.fax = fax;
		this.mapUrl = mapUrl;
		this.address = address;
		this.rootUser = rootUser;
		this.ppType = ppType;
		this.EBuildses = EBuildses;
		this.analysisClientComeGos = analysisClientComeGos;
	}

	// Property accessors

	public Integer getLpId() {
		return this.lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public String getLpCode() {
		return this.lpCode;
	}

	public void setLpCode(String lpCode) {
		this.lpCode = lpCode;
	}

	public String getLpName() {
		return this.lpName;
	}

	public void setLpName(String lpName) {
		this.lpName = lpName;
	}

	public String getRegional() {
		return this.regional;
	}

	public void setRegional(String regional) {
		this.regional = regional;
	}

	public String getDevelopCompany() {
		return this.developCompany;
	}

	public void setDevelopCompany(String developCompany) {
		this.developCompany = developCompany;
	}

	public String getDesignCompany() {
		return this.designCompany;
	}

	public void setDesignCompany(String designCompany) {
		this.designCompany = designCompany;
	}

	public String getBuildCompany() {
		return this.buildCompany;
	}

	public void setBuildCompany(String buildCompany) {
		this.buildCompany = buildCompany;
	}

	public float getConstructionArea() {
		return this.constructionArea;
	}

	public void setConstructionArea(float constructionArea) {
		this.constructionArea = constructionArea;
	}

	public float getUseArea() {
		return this.useArea;
	}

	public void setUseArea(float useArea) {
		this.useArea = useArea;
	}

	public float getVirescenceArea() {
		return this.virescenceArea;
	}

	public void setVirescenceArea(float virescenceArea) {
		this.virescenceArea = virescenceArea;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getUseDate() {
		return this.useDate;
	}

	public void setUseDate(String useDate) {
		this.useDate = useDate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMapUrl() {
		return this.mapUrl;
	}

	public void setMapUrl(String mapUrl) {
		this.mapUrl = mapUrl;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getPpType() {
		return this.ppType;
	}

	public void setPpType(String ppType) {
		this.ppType = ppType;
	}

	public Set getEBuildses() {
		return this.EBuildses;
	}

	public void setEBuildses(Set EBuildses) {
		this.EBuildses = EBuildses;
	}

	public Set getAnalysisClientComeGos() {
		return this.analysisClientComeGos;
	}

	public void setAnalysisClientComeGos(Set analysisClientComeGos) {
		this.analysisClientComeGos = analysisClientComeGos;
	}

}