package com.zc13.bkmis.mapping;

/**
 * ERoomFixture generated by MyEclipse Persistence Tools
 */

public class ERoomFixture implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer roomId;
	private Integer fixtureId;
	private Integer amount;
	private String bz;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public ERoomFixture() {
	}

	// Property accessors

	public ERoomFixture(Integer id, Integer roomId, Integer fixtureId, Integer amount, String bz, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.roomId = roomId;
		this.fixtureId = fixtureId;
		this.amount = amount;
		this.bz = bz;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public Integer getFixtureId() {
		return this.fixtureId;
	}

	public void setFixtureId(Integer fixtureId) {
		this.fixtureId = fixtureId;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}