package com.zc13.bkmis.mapping;

/**
 * ERoomClient generated by MyEclipse Persistence Tools
 */

public class ERoomClient implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer roomId;
	private Integer clientId;
	private Integer pactId;
	private String beginDate;
	private String endDate;
	private String clientName;
	private String clientType;
	private String unitName;
	private String linkName;
	private String phone;
	private String status;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public ERoomClient() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public ERoomClient(Integer id, Integer roomId, Integer clientId, Integer pactId, String beginDate, String endDate, String clientName, String clientType, String unitName, String linkName, String phone, String status, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.roomId = roomId;
		this.clientId = clientId;
		this.pactId = pactId;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.clientName = clientName;
		this.clientType = clientType;
		this.unitName = unitName;
		this.linkName = linkName;
		this.phone = phone;
		this.status = status;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public Integer getPactId() {
		return this.pactId;
	}

	public void setPactId(Integer pactId) {
		this.pactId = pactId;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}