package com.zc13.bkmis.mapping;

import java.util.HashSet;
import java.util.Set;

/**
 * ERooms generated by MyEclipse Persistence Tools
 */

public class ERooms implements java.io.Serializable {

	// Fields

	private Integer roomId;
	private EBuilds EBuilds;
	private String roomCode;
	private String roomFullName;
	private String unitId;
	private String floor;
	private float constructionArea;
	private float useArea;
	private String toward;
	private String roomType;
	private String status;
	private String regional;
	private String phoneNumber;
	private String bz;
	private Integer lpId;
	private Integer rootUser;
	private Set compactRoomCoststandards = new HashSet(0);
	private Set CBills = new HashSet(0);

	// Constructors

	public ERooms(Integer roomId, EBuilds builds, String roomCode,
			String roomFullName, String unitId, String floor,
			float constructionArea, float useArea, String toward,
			String roomType, String status, String regional,
			String phoneNumber, String bz, Integer lpId, Integer rootUser,
			Set compactRoomCoststandards, Set bills) {
		super();
		this.roomId = roomId;
		EBuilds = builds;
		this.roomCode = roomCode;
		this.roomFullName = roomFullName;
		this.unitId = unitId;
		this.floor = floor;
		this.constructionArea = constructionArea;
		this.useArea = useArea;
		this.toward = toward;
		this.roomType = roomType;
		this.status = status;
		this.regional = regional;
		this.phoneNumber = phoneNumber;
		this.bz = bz;
		this.lpId = lpId;
		this.rootUser = rootUser;
		this.compactRoomCoststandards = compactRoomCoststandards;
		CBills = bills;
	}

	/** default constructor */
	public ERooms() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public EBuilds getEBuilds() {
		return this.EBuilds;
	}

	public void setEBuilds(EBuilds EBuilds) {
		this.EBuilds = EBuilds;
	}

	public String getRoomCode() {
		return this.roomCode;
	}

	public void setRoomCode(String roomCode) {
		this.roomCode = roomCode;
	}

	public String getRoomFullName() {
		return this.roomFullName;
	}

	public void setRoomFullName(String roomFullName) {
		this.roomFullName = roomFullName;
	}

	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public float getConstructionArea() {
		return this.constructionArea;
	}

	public void setConstructionArea(float constructionArea) {
		this.constructionArea = constructionArea;
	}

	public float getUseArea() {
		return this.useArea;
	}

	public void setUseArea(float useArea) {
		this.useArea = useArea;
	}

	public String getToward() {
		return this.toward;
	}

	public void setToward(String toward) {
		this.toward = toward;
	}

	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRegional() {
		return this.regional;
	}

	public void setRegional(String regional) {
		this.regional = regional;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public Set getCompactRoomCoststandards() {
		return this.compactRoomCoststandards;
	}

	public void setCompactRoomCoststandards(Set compactRoomCoststandards) {
		this.compactRoomCoststandards = compactRoomCoststandards;
	}

	public Set getCBills() {
		return this.CBills;
	}

	public void setCBills(Set CBills) {
		this.CBills = CBills;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}