package com.zc13.bkmis.mapping;

/**
 * HrExteriorPersonnel generated by MyEclipse Persistence Tools
 */

public class HrExteriorPersonnel implements java.io.Serializable {

	// Fields

	private Integer id;
	private String name;
	private String sex;
	private String natioanality;
	private String birtyday;
	private Integer age;
	private String nativePalace;
	private String foreignDegree;
	private String nativeDegree;
	private String identityCard;
	private String phone;
	private String currentCountry;
	private String researchTopic;
	private String joincompanyType;
	private String company;
	private String imageUrl;
	private String researchResult;
	private String researchField;
	private String getRewart;
	private String mailbox;
	private String resolveProblem;
	private String post;
	private String homecomingDisposition;
	private String address;
	private String enjoyPolicy;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public HrExteriorPersonnel() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public HrExteriorPersonnel(Integer id, String name, String sex, String natioanality, String birtyday, Integer age, String nativePalace, String foreignDegree, String nativeDegree, String identityCard, String phone, String currentCountry, String researchTopic, String joincompanyType, String company, String imageUrl, String researchResult, String researchField, String getRewart, String mailbox, String resolveProblem, String post, String homecomingDisposition, String address,
			String enjoyPolicy, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.name = name;
		this.sex = sex;
		this.natioanality = natioanality;
		this.birtyday = birtyday;
		this.age = age;
		this.nativePalace = nativePalace;
		this.foreignDegree = foreignDegree;
		this.nativeDegree = nativeDegree;
		this.identityCard = identityCard;
		this.phone = phone;
		this.currentCountry = currentCountry;
		this.researchTopic = researchTopic;
		this.joincompanyType = joincompanyType;
		this.company = company;
		this.imageUrl = imageUrl;
		this.researchResult = researchResult;
		this.researchField = researchField;
		this.getRewart = getRewart;
		this.mailbox = mailbox;
		this.resolveProblem = resolveProblem;
		this.post = post;
		this.homecomingDisposition = homecomingDisposition;
		this.address = address;
		this.enjoyPolicy = enjoyPolicy;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getNatioanality() {
		return this.natioanality;
	}

	public void setNatioanality(String natioanality) {
		this.natioanality = natioanality;
	}

	public String getBirtyday() {
		return this.birtyday;
	}

	public void setBirtyday(String birtyday) {
		this.birtyday = birtyday;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getNativePalace() {
		return this.nativePalace;
	}

	public void setNativePalace(String nativePalace) {
		this.nativePalace = nativePalace;
	}

	public String getForeignDegree() {
		return this.foreignDegree;
	}

	public void setForeignDegree(String foreignDegree) {
		this.foreignDegree = foreignDegree;
	}

	public String getNativeDegree() {
		return this.nativeDegree;
	}

	public void setNativeDegree(String nativeDegree) {
		this.nativeDegree = nativeDegree;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCurrentCountry() {
		return this.currentCountry;
	}

	public void setCurrentCountry(String currentCountry) {
		this.currentCountry = currentCountry;
	}

	public String getResearchTopic() {
		return this.researchTopic;
	}

	public void setResearchTopic(String researchTopic) {
		this.researchTopic = researchTopic;
	}

	public String getJoincompanyType() {
		return this.joincompanyType;
	}

	public void setJoincompanyType(String joincompanyType) {
		this.joincompanyType = joincompanyType;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getResearchResult() {
		return this.researchResult;
	}

	public void setResearchResult(String researchResult) {
		this.researchResult = researchResult;
	}

	public String getResearchField() {
		return this.researchField;
	}

	public void setResearchField(String researchField) {
		this.researchField = researchField;
	}

	public String getGetRewart() {
		return this.getRewart;
	}

	public void setGetRewart(String getRewart) {
		this.getRewart = getRewart;
	}

	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}

	public String getResolveProblem() {
		return this.resolveProblem;
	}

	public void setResolveProblem(String resolveProblem) {
		this.resolveProblem = resolveProblem;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getHomecomingDisposition() {
		return this.homecomingDisposition;
	}

	public void setHomecomingDisposition(String homecomingDisposition) {
		this.homecomingDisposition = homecomingDisposition;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEnjoyPolicy() {
		return this.enjoyPolicy;
	}

	public void setEnjoyPolicy(String enjoyPolicy) {
		this.enjoyPolicy = enjoyPolicy;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}