package com.zc13.bkmis.mapping;

/**
 * HrFile generated by MyEclipse Persistence Tools
 */

public class HrFile implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer pactId;
	private String fileName;
	private String url;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public HrFile() {
	}

	// Property accessors

	public HrFile(Integer id, Integer pactId, String fileName, String url, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.pactId = pactId;
		this.fileName = fileName;
		this.url = url;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getPactId() {
		return pactId;
	}

	public void setPactId(Integer pactId) {
		this.pactId = pactId;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}