package com.zc13.bkmis.mapping;

/**
 * HrPact generated by MyEclipse Persistence Tools
 */

public class HrPact implements java.io.Serializable {

	// Fields

	private Integer pactId;
	private Integer personnelId;
	private String pactCode;
	private String engageChannel;
	private String recommendPerson;
	private String departmentCode;
	private String duty;
	private String pactMakeDate;
	private String pactBeginDate;
	private String pactEndDate;
	private String startDate;
	private String tryoutEndDate;
	private String pactFile;
	private String pactFileName;
	private String identityCopy;
	private String identityCopyName;
	private String academicCertificateCopy;
	private String academicCertificateCopyName;
	private String physicalExaminationReport;
	private String physicalExaminationReportName;
	private String qualificationCertificateCopy;
	private String qualificationCertificateCopyName;
	private String bankCardCopy;
	private String bankCardCopyName;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public HrPact() {
	}

	// Property accessors

	public HrPact(Integer pactId, Integer personnelId, String pactCode, String engageChannel, String recommendPerson, String departmentCode, String duty, String pactMakeDate, String pactBeginDate, String pactEndDate, String startDate, String tryoutEndDate, String pactFile, String pactFileName, String identityCopy, String identityCopyName, String academicCertificateCopy, String academicCertificateCopyName, String physicalExaminationReport, String physicalExaminationReportName,
			String qualificationCertificateCopy, String qualificationCertificateCopyName, String bankCardCopy, String bankCardCopyName, Integer lpId, Integer rootUser) {
		super();
		this.pactId = pactId;
		this.personnelId = personnelId;
		this.pactCode = pactCode;
		this.engageChannel = engageChannel;
		this.recommendPerson = recommendPerson;
		this.departmentCode = departmentCode;
		this.duty = duty;
		this.pactMakeDate = pactMakeDate;
		this.pactBeginDate = pactBeginDate;
		this.pactEndDate = pactEndDate;
		this.startDate = startDate;
		this.tryoutEndDate = tryoutEndDate;
		this.pactFile = pactFile;
		this.pactFileName = pactFileName;
		this.identityCopy = identityCopy;
		this.identityCopyName = identityCopyName;
		this.academicCertificateCopy = academicCertificateCopy;
		this.academicCertificateCopyName = academicCertificateCopyName;
		this.physicalExaminationReport = physicalExaminationReport;
		this.physicalExaminationReportName = physicalExaminationReportName;
		this.qualificationCertificateCopy = qualificationCertificateCopy;
		this.qualificationCertificateCopyName = qualificationCertificateCopyName;
		this.bankCardCopy = bankCardCopy;
		this.bankCardCopyName = bankCardCopyName;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public Integer getPersonnelId() {
		return personnelId;
	}

	public void setPersonnelId(Integer personnelId) {
		this.personnelId = personnelId;
	}

	public Integer getPactId() {
		return this.pactId;
	}

	public void setPactId(Integer pactId) {
		this.pactId = pactId;
	}

	public String getPactCode() {
		return this.pactCode;
	}

	public void setPactCode(String pactCode) {
		this.pactCode = pactCode;
	}

	public String getEngageChannel() {
		return this.engageChannel;
	}

	public void setEngageChannel(String engageChannel) {
		this.engageChannel = engageChannel;
	}

	public String getRecommendPerson() {
		return this.recommendPerson;
	}

	public void setRecommendPerson(String recommendPerson) {
		this.recommendPerson = recommendPerson;
	}

	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getPactMakeDate() {
		return this.pactMakeDate;
	}

	public void setPactMakeDate(String pactMakeDate) {
		this.pactMakeDate = pactMakeDate;
	}

	public String getPactBeginDate() {
		return this.pactBeginDate;
	}

	public void setPactBeginDate(String pactBeginDate) {
		this.pactBeginDate = pactBeginDate;
	}

	public String getPactEndDate() {
		return this.pactEndDate;
	}

	public void setPactEndDate(String pactEndDate) {
		this.pactEndDate = pactEndDate;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getTryoutEndDate() {
		return this.tryoutEndDate;
	}

	public void setTryoutEndDate(String tryoutEndDate) {
		this.tryoutEndDate = tryoutEndDate;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public String getPactFile() {
		return this.pactFile;
	}

	public void setPactFile(String pactFile) {
		this.pactFile = pactFile;
	}

	public String getPactFileName() {
		return this.pactFileName;
	}

	public void setPactFileName(String pactFileName) {
		this.pactFileName = pactFileName;
	}

	public String getIdentityCopy() {
		return this.identityCopy;
	}

	public void setIdentityCopy(String identityCopy) {
		this.identityCopy = identityCopy;
	}

	public String getIdentityCopyName() {
		return this.identityCopyName;
	}

	public void setIdentityCopyName(String identityCopyName) {
		this.identityCopyName = identityCopyName;
	}

	public String getAcademicCertificateCopy() {
		return this.academicCertificateCopy;
	}

	public void setAcademicCertificateCopy(String academicCertificateCopy) {
		this.academicCertificateCopy = academicCertificateCopy;
	}

	public String getAcademicCertificateCopyName() {
		return this.academicCertificateCopyName;
	}

	public void setAcademicCertificateCopyName(
			String academicCertificateCopyName) {
		this.academicCertificateCopyName = academicCertificateCopyName;
	}

	public String getPhysicalExaminationReport() {
		return this.physicalExaminationReport;
	}

	public void setPhysicalExaminationReport(String physicalExaminationReport) {
		this.physicalExaminationReport = physicalExaminationReport;
	}

	public String getPhysicalExaminationReportName() {
		return this.physicalExaminationReportName;
	}

	public void setPhysicalExaminationReportName(
			String physicalExaminationReportName) {
		this.physicalExaminationReportName = physicalExaminationReportName;
	}

	public String getQualificationCertificateCopy() {
		return this.qualificationCertificateCopy;
	}

	public void setQualificationCertificateCopy(
			String qualificationCertificateCopy) {
		this.qualificationCertificateCopy = qualificationCertificateCopy;
	}

	public String getQualificationCertificateCopyName() {
		return this.qualificationCertificateCopyName;
	}

	public void setQualificationCertificateCopyName(
			String qualificationCertificateCopyName) {
		this.qualificationCertificateCopyName = qualificationCertificateCopyName;
	}

	public String getBankCardCopy() {
		return this.bankCardCopy;
	}

	public void setBankCardCopy(String bankCardCopy) {
		this.bankCardCopy = bankCardCopy;
	}

	public String getBankCardCopyName() {
		return this.bankCardCopyName;
	}

	public void setBankCardCopyName(String bankCardCopyName) {
		this.bankCardCopyName = bankCardCopyName;
	}

}