package com.zc13.bkmis.mapping;

/**
 * AnalysisClientComeGo generated by MyEclipse Persistence Tools
 */

public class MerchantsPlan implements java.io.Serializable {

	// Fields

	private Integer id;
	private String year;
	private String month;
	private double area;
	private String quarter;
	private Integer createUser;
	private String responsePerson;
	private String personType;

	// Constructors

	/** default constructor */
	public MerchantsPlan() {
	}

	/** full constructor */
	public MerchantsPlan(String year,String month,float area,String quarter,Integer createUser,String responsePerson,String personType) {
		this.year=year;
		this.month=month;
		this.area=area;
		this.quarter=quarter;
		this.createUser=createUser;
		this.responsePerson=responsePerson;
		this.personType=personType;
	}



	public String getPersonType() {
		return personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public String getResponsePerson() {
		return responsePerson;
	}

	public void setResponsePerson(String responsePerson) {
		this.responsePerson = responsePerson;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public double getArea() {
		return area;
	}

	public void setArea(double area) {
		this.area = area;
	}

	public String getQuarter() {
		return quarter;
	}

	public void setQuarter(String quarter) {
		this.quarter = quarter;
	}

	public Integer getCreateUser() {
		return createUser;
	}

	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}
}