package com.zc13.bkmis.mapping;

/**
 * ViewTreeCodeId generated by MyEclipse Persistence Tools
 */

public class OperateCost implements java.io.Serializable {

	// Fields

	private Integer id;
	private String year;
	private String month;
	private String moneyType;
	private double cleanFee;
	private double securityFee;
	private double communicationFee;
	private double waterFee;
	private double electricityFee;
	private double materials;
	private double eqmCheckFee;
	private double otherFee;
	/**13-06-17 加入了燃气费*/
	private double gasFee;

	// Constructors

	/** default constructor */
	public OperateCost() {
	}

	/** full constructor */
	public OperateCost(Integer id, String year,String month, String moneyType,double cleanFee,double securityFee,double communicationFee,double waterFee,double electricityFee,double materials,double eqmCheckFee,double otherFee,double gasFee) {
		this.id = id;
		this.year = year;
		this.month = month;
		this.moneyType = moneyType;
		this.cleanFee = cleanFee;
		this.securityFee = securityFee;
		this.communicationFee = communicationFee;
		this.waterFee = waterFee;
		this.electricityFee = electricityFee;
		this.materials = materials;
		this.eqmCheckFee = eqmCheckFee;
		this.otherFee = otherFee;
		this.gasFee = gasFee;
	}

	public double getGasFee() {
		return gasFee;
	}

	public void setGasFee(double gasFee) {
		this.gasFee = gasFee;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getMoneyType() {
		return moneyType;
	}

	public void setMoneyType(String moneyType) {
		this.moneyType = moneyType;
	}

	public double getCleanFee() {
		return cleanFee;
	}

	public void setCleanFee(double cleanFee) {
		this.cleanFee = cleanFee;
	}

	public double getSecurityFee() {
		return securityFee;
	}

	public void setSecurityFee(double securityFee) {
		this.securityFee = securityFee;
	}

	public double getCommunicationFee() {
		return communicationFee;
	}

	public void setCommunicationFee(double communicationFee) {
		this.communicationFee = communicationFee;
	}

	public double getWaterFee() {
		return waterFee;
	}

	public void setWaterFee(double waterFee) {
		this.waterFee = waterFee;
	}

	public double getElectricityFee() {
		return electricityFee;
	}

	public void setElectricityFee(double electricityFee) {
		this.electricityFee = electricityFee;
	}

	public double getMaterials() {
		return materials;
	}

	public void setMaterials(double materials) {
		this.materials = materials;
	}

	public double getEqmCheckFee() {
		return eqmCheckFee;
	}

	public void setEqmCheckFee(double eqmCheckFee) {
		this.eqmCheckFee = eqmCheckFee;
	}

	public double getOtherFee() {
		return otherFee;
	}

	public void setOtherFee(double otherFee) {
		this.otherFee = otherFee;
	}

}