package com.zc13.bkmis.mapping;

/**
 * ViewTreeCodeId generated by MyEclipse Persistence Tools
 */

public class OperateIncome implements java.io.Serializable {

	// Fields

	private Integer id;
	private String year;
	private String month;
	private String moneyType;
	private double rentFee;
	private double decorationFee;
	private double communicationFee;
	private double electricityFee;
	private double stopCarFee;
	private double otherFee;
	private double heatFee;
	private double propertyFee;

	// Constructors

	/** default constructor */
	public OperateIncome() {
	}

	/** full constructor */
	public OperateIncome(Integer id, String year,String month, String moneyType,double rentFee,double decorationFee,double communicationFee,double electricityFee,double stopCarFee,double otherFee,double heatFee,double propertyFee) {
		this.id = id;
		this.year = year;
		this.month = month;
		this.moneyType = moneyType;
		this.rentFee = rentFee;
		this.decorationFee = decorationFee;
		this.communicationFee = communicationFee;
		this.electricityFee = electricityFee;
		this.stopCarFee = stopCarFee;
		this.heatFee = heatFee;
		this.otherFee = otherFee;
		this.propertyFee = propertyFee;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getMoneyType() {
		return moneyType;
	}

	public void setMoneyType(String moneyType) {
		this.moneyType = moneyType;
	}

	public double getRentFee() {
		return rentFee;
	}

	public void setRentFee(double rentFee) {
		this.rentFee = rentFee;
	}

	public double getDecorationFee() {
		return decorationFee;
	}

	public void setDecorationFee(double decorationFee) {
		this.decorationFee = decorationFee;
	}

	public double getCommunicationFee() {
		return communicationFee;
	}

	public void setCommunicationFee(double communicationFee) {
		this.communicationFee = communicationFee;
	}

	public double getElectricityFee() {
		return electricityFee;
	}

	public void setElectricityFee(double electricityFee) {
		this.electricityFee = electricityFee;
	}

	public double getStopCarFee() {
		return stopCarFee;
	}

	public void setStopCarFee(double stopCarFee) {
		this.stopCarFee = stopCarFee;
	}

	public double getOtherFee() {
		return otherFee;
	}

	public void setOtherFee(double otherFee) {
		this.otherFee = otherFee;
	}

	public double getHeatFee() {
		return heatFee;
	}

	public void setHeatFee(double heatFee) {
		this.heatFee = heatFee;
	}

	public double getPropertyFee() {
		return propertyFee;
	}

	public void setPropertyFee(double propertyFee) {
		this.propertyFee = propertyFee;
	}

}