package com.zc13.bkmis.mapping;

/**
 * ViewTreeCodeId generated by MyEclipse Persistence Tools
 */

public class ProjectCosts implements java.io.Serializable {

	// Fields

	private Integer id;
	private String year;
	private String month;
	private String moneyType;
	private String department;
	private double copeWage;
	private double copeWelfare;
	private double unionFunds;
	private double educationFunds;
	private double supplementaryMedical;
	private double enterpriseAnnuity;
	private double pensionInsurance;
	private double healthInsurance;
	private double housingFund;
	private double unemployInsurance;
	private double injuryInsurance;
	private double maternityInsurance;
	private double trafficFee;
	private double phoneFee;
	private double depreciationFee;
	private double hospitalityFee;
	private double travelFee;
	private double officeFee;
	private double auditFee;
	private double boardFee;
	private double stampDuty;
	private double conferenceFee;
	private double otherFee;
	private double glfHj;
	private double estateFee;
	private double landTax;
	private double propertyTax;

	// Constructors

	/** default constructor */
	public ProjectCosts() {
	}

	/** full constructor */
	public ProjectCosts(Integer id,String year,String month, String moneyType,String department,double copeWage,double copeWelfare,
			double unionFunds,double educationFunds,double supplementaryMedical,double enterpriseAnnuity,
			double pensionInsurance,
			double healthInsurance,double housingFund,double unemployInsurance,double injuryInsurance,
			double maternityInsurance,double trafficFee,double phoneFee,double depreciationFee,
			double hospitalityFee,double travelFee,double officeFee,double auditFee,
			double boardFee,double stampDuty,double conferenceFee,
			double otherFee,double glfHj,double estateFee,double landTax,double propertyTax) {
		this.id = id;
		this.year = year;
		this.month = month;
		this.moneyType = moneyType;
		this.department = department;
		this.copeWage = copeWage;
		this.copeWelfare = copeWelfare;
		this.unionFunds = unionFunds;
		this.educationFunds = educationFunds;
		this.supplementaryMedical = supplementaryMedical;
		this.enterpriseAnnuity = enterpriseAnnuity;
		this.pensionInsurance = pensionInsurance;
		this.healthInsurance = healthInsurance;
		this.housingFund = housingFund;
		this.unemployInsurance = unemployInsurance;
		this.injuryInsurance = injuryInsurance;
		this.maternityInsurance = maternityInsurance;
		this.trafficFee = trafficFee;
		this.phoneFee = phoneFee;
		this.depreciationFee = depreciationFee;
		this.hospitalityFee = hospitalityFee;
		this.travelFee = travelFee;
		this.officeFee = officeFee;
		this.auditFee = auditFee;
		this.boardFee = boardFee;
		this.stampDuty = stampDuty;
		this.conferenceFee = conferenceFee;
		this.otherFee = otherFee;
		this.glfHj = glfHj;
		this.estateFee = estateFee;
		this.landTax = landTax;
		this.propertyTax = propertyTax;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getMoneyType() {
		return moneyType;
	}

	public void setMoneyType(String moneyType) {
		this.moneyType = moneyType;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public double getCopeWage() {
		return copeWage;
	}

	public void setCopeWage(double copeWage) {
		this.copeWage = copeWage;
	}

	public double getCopeWelfare() {
		return copeWelfare;
	}

	public void setCopeWelfare(double copeWelfare) {
		this.copeWelfare = copeWelfare;
	}

	public double getUnionFunds() {
		return unionFunds;
	}

	public void setUnionFunds(double unionFunds) {
		this.unionFunds = unionFunds;
	}

	public double getEducationFunds() {
		return educationFunds;
	}

	public void setEducationFunds(double educationFunds) {
		this.educationFunds = educationFunds;
	}

	public double getSupplementaryMedical() {
		return supplementaryMedical;
	}

	public void setSupplementaryMedical(double supplementaryMedical) {
		this.supplementaryMedical = supplementaryMedical;
	}

	public double getEnterpriseAnnuity() {
		return enterpriseAnnuity;
	}

	public void setEnterpriseAnnuity(double enterpriseAnnuity) {
		this.enterpriseAnnuity = enterpriseAnnuity;
	}

	public double getPensionInsurance() {
		return pensionInsurance;
	}

	public void setPensionInsurance(double pensionInsurance) {
		this.pensionInsurance = pensionInsurance;
	}

	public double getHealthInsurance() {
		return healthInsurance;
	}

	public void setHealthInsurance(double healthInsurance) {
		this.healthInsurance = healthInsurance;
	}

	public double getHousingFund() {
		return housingFund;
	}

	public void setHousingFund(double housingFund) {
		this.housingFund = housingFund;
	}

	public double getUnemployInsurance() {
		return unemployInsurance;
	}

	public void setUnemployInsurance(double unemployInsurance) {
		this.unemployInsurance = unemployInsurance;
	}

	public double getInjuryInsurance() {
		return injuryInsurance;
	}

	public void setInjuryInsurance(double injuryInsurance) {
		this.injuryInsurance = injuryInsurance;
	}

	public double getMaternityInsurance() {
		return maternityInsurance;
	}

	public void setMaternityInsurance(double maternityInsurance) {
		this.maternityInsurance = maternityInsurance;
	}

	public double getTrafficFee() {
		return trafficFee;
	}

	public void setTrafficFee(double trafficFee) {
		this.trafficFee = trafficFee;
	}

	public double getPhoneFee() {
		return phoneFee;
	}

	public void setPhoneFee(double phoneFee) {
		this.phoneFee = phoneFee;
	}

	public double getDepreciationFee() {
		return depreciationFee;
	}

	public void setDepreciationFee(double depreciationFee) {
		this.depreciationFee = depreciationFee;
	}

	public double getHospitalityFee() {
		return hospitalityFee;
	}

	public void setHospitalityFee(double hospitalityFee) {
		this.hospitalityFee = hospitalityFee;
	}

	public double getTravelFee() {
		return travelFee;
	}

	public void setTravelFee(double travelFee) {
		this.travelFee = travelFee;
	}

	public double getOfficeFee() {
		return officeFee;
	}

	public void setOfficeFee(double officeFee) {
		this.officeFee = officeFee;
	}

	public double getAuditFee() {
		return auditFee;
	}

	public void setAuditFee(double auditFee) {
		this.auditFee = auditFee;
	}

	public double getBoardFee() {
		return boardFee;
	}

	public void setBoardFee(double boardFee) {
		this.boardFee = boardFee;
	}

	public double getStampDuty() {
		return stampDuty;
	}

	public void setStampDuty(double stampDuty) {
		this.stampDuty = stampDuty;
	}

	public double getConferenceFee() {
		return conferenceFee;
	}

	public void setConferenceFee(double conferenceFee) {
		this.conferenceFee = conferenceFee;
	}

	public double getOtherFee() {
		return otherFee;
	}

	public void setOtherFee(double otherFee) {
		this.otherFee = otherFee;
	}

	public double getGlfHj() {
		return glfHj;
	}

	public void setGlfHj(double glfHj) {
		this.glfHj = glfHj;
	}

	public double getEstateFee() {
		return estateFee;
	}

	public void setEstateFee(double estateFee) {
		this.estateFee = estateFee;
	}

	public double getLandTax() {
		return landTax;
	}

	public void setLandTax(double landTax) {
		this.landTax = landTax;
	}

	public double getPropertyTax() {
		return propertyTax;
	}

	public void setPropertyTax(double propertyTax) {
		this.propertyTax = propertyTax;
	}
}