package com.zc13.bkmis.mapping;

/**
 * SerClientComplaint generated by MyEclipse Persistence Tools
 */

public class SerClientComplaint implements java.io.Serializable {

	// Fields

	private Integer id;
	private String type;
	private String name;
	private String phone;
	private String roomCode;
	private String complaintContent;
	private String complaintDate;
	private String clerk;
	private String code;
	private String status;
	private String verifyContent;
	private String verifyResult;
	private String verifyMan;
	private String verifyDate;
	private String disposalWay;
	private String disposalDate;
	private String disposalResult;
	private String dutyMan;
	private String ownerOpinion;
	private String leadOpinion;
	private String generalOpinion;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public SerClientComplaint() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public SerClientComplaint(Integer id, String type, String name, String phone, String roomCode, String complaintContent, String complaintDate, String clerk, String code, String status, String verifyContent, String verifyResult, String verifyMan, String verifyDate, String disposalWay, String disposalDate, String disposalResult, String dutyMan, String ownerOpinion, String leadOpinion, String generalOpinion, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.type = type;
		this.name = name;
		this.phone = phone;
		this.roomCode = roomCode;
		this.complaintContent = complaintContent;
		this.complaintDate = complaintDate;
		this.clerk = clerk;
		this.code = code;
		this.status = status;
		this.verifyContent = verifyContent;
		this.verifyResult = verifyResult;
		this.verifyMan = verifyMan;
		this.verifyDate = verifyDate;
		this.disposalWay = disposalWay;
		this.disposalDate = disposalDate;
		this.disposalResult = disposalResult;
		this.dutyMan = dutyMan;
		this.ownerOpinion = ownerOpinion;
		this.leadOpinion = leadOpinion;
		this.generalOpinion = generalOpinion;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRoomCode() {
		return this.roomCode;
	}

	public void setRoomCode(String roomCode) {
		this.roomCode = roomCode;
	}

	public String getComplaintContent() {
		return this.complaintContent;
	}

	public void setComplaintContent(String complaintContent) {
		this.complaintContent = complaintContent;
	}

	public String getComplaintDate() {
		return this.complaintDate;
	}

	public void setComplaintDate(String complaintDate) {
		this.complaintDate = complaintDate;
	}

	public String getClerk() {
		return this.clerk;
	}

	public void setClerk(String clerk) {
		this.clerk = clerk;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getVerifyContent() {
		return this.verifyContent;
	}

	public void setVerifyContent(String verifyContent) {
		this.verifyContent = verifyContent;
	}

	public String getVerifyResult() {
		return this.verifyResult;
	}

	public void setVerifyResult(String verifyResult) {
		this.verifyResult = verifyResult;
	}

	public String getVerifyMan() {
		return this.verifyMan;
	}

	public void setVerifyMan(String verifyMan) {
		this.verifyMan = verifyMan;
	}

	public String getVerifyDate() {
		return this.verifyDate;
	}

	public void setVerifyDate(String verifyDate) {
		this.verifyDate = verifyDate;
	}

	public String getDisposalWay() {
		return this.disposalWay;
	}

	public void setDisposalWay(String disposalWay) {
		this.disposalWay = disposalWay;
	}

	public String getDisposalDate() {
		return this.disposalDate;
	}

	public void setDisposalDate(String disposalDate) {
		this.disposalDate = disposalDate;
	}

	public String getDisposalResult() {
		return this.disposalResult;
	}

	public void setDisposalResult(String disposalResult) {
		this.disposalResult = disposalResult;
	}

	public String getDutyMan() {
		return this.dutyMan;
	}

	public void setDutyMan(String dutyMan) {
		this.dutyMan = dutyMan;
	}

	public String getOwnerOpinion() {
		return this.ownerOpinion;
	}

	public void setOwnerOpinion(String ownerOpinion) {
		this.ownerOpinion = ownerOpinion;
	}

	public String getLeadOpinion() {
		return this.leadOpinion;
	}

	public void setLeadOpinion(String leadOpinion) {
		this.leadOpinion = leadOpinion;
	}

	public String getGeneralOpinion() {
		return this.generalOpinion;
	}

	public void setGeneralOpinion(String generalOpinion) {
		this.generalOpinion = generalOpinion;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

}