package com.zc13.bkmis.mapping;

/**
 * SerMaintainProject generated by MyEclipse Persistence Tools
 */

public class SerMaintainProject implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String name;
	private String type;
	private String chargeType;
	private float rate;
	private float responseTime;
	private String bz;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public SerMaintainProject() {
	}
 
	// Property accessors

	public SerMaintainProject(Integer id, String code, String name, String type, String chargeType, float rate, float responseTime, String bz, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.name = name;
		this.type = type;
		this.chargeType = chargeType;
		this.rate = rate;
		this.responseTime = responseTime;
		this.bz = bz;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public float getRate() {
		return this.rate;
	}

	public void setRate(float rate) {
		this.rate = rate;
	}

	public float getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(float responseTime) {
		this.responseTime = responseTime;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public Integer getRootUser() {
		return this.rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getChargeType() {
		return chargeType;
	}

	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

}