package com.zc13.bkmis.mapping;

/**
 * SysSequence generated by MyEclipse Persistence Tools
 */

public class SysSequence implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String value;
	private Integer lpId;
	private Integer rootUser;

	// Constructors

	/** default constructor */
	public SysSequence() {
	}

	// Property accessors

	public Integer getLpId() {
		return lpId;
	}

	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	public Integer getRootUser() {
		return rootUser;
	}

	public void setRootUser(Integer rootUser) {
		this.rootUser = rootUser;
	}

	public SysSequence(Integer id, String code, String value, Integer lpId, Integer rootUser) {
		super();
		this.id = id;
		this.code = code;
		this.value = value;
		this.lpId = lpId;
		this.rootUser = rootUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}