package com.zc13.bkmis.mapping;

/**
 * ViewTreeCodeId generated by MyEclipse Persistence Tools
 */

public class ViewTreeCodeId implements java.io.Serializable {

	// Fields

	private Integer pk;
	private Integer id;
	private String name;
	private Integer parentId;
	private String tableName;

	// Constructors

	/** default constructor */
	public ViewTreeCodeId() {
	}

	/** minimal constructor */
	public ViewTreeCodeId(Integer pk, String tableName) {
		this.pk = pk;
		this.tableName = tableName;
	}

	/** full constructor */
	public ViewTreeCodeId(Integer pk, Integer id, String name,
			Integer parentId, String tableName) {
		this.pk = pk;
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.tableName = tableName;
	}

	// Property accessors

	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewTreeCodeId))
			return false;
		ViewTreeCodeId castOther = (ViewTreeCodeId) other;

		return ((this.getPk() == castOther.getPk()) || (this.getPk() != null
				&& castOther.getPk() != null && this.getPk().equals(
				castOther.getPk())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getParentId() == castOther.getParentId()) || (this
						.getParentId() != null
						&& castOther.getParentId() != null && this
						.getParentId().equals(castOther.getParentId())))
				&& ((this.getTableName() == castOther.getTableName()) || (this
						.getTableName() != null
						&& castOther.getTableName() != null && this
						.getTableName().equals(castOther.getTableName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPk() == null ? 0 : this.getPk().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getParentId() == null ? 0 : this.getParentId().hashCode());
		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		return result;
	}

}