package com.zc13.bkmis.mapping;

/**
 * ViewBuild generated by MyEclipse Persistence Tools
 */

public class ViewBuild implements java.io.Serializable {

	// Fields

	private ViewBuildId id;

	// Constructors

	/** default constructor */
	public ViewBuild() {
	}

	/** full constructor */
	public ViewBuild(ViewBuildId id) {
		this.id = id;
	}

	// Property accessors

	public ViewBuildId getId() {
		return this.id;
	}

	public void setId(ViewBuildId id) {
		this.id = id;
	}

}