package com.zc13.bkmis.mapping;

/**
 * ViewTreeCode generated by MyEclipse Persistence Tools
 */

public class ViewTreeCode implements java.io.Serializable {

	// Fields

	private ViewTreeCodeId id;

	// Constructors

	/** default constructor */
	public ViewTreeCode() {
	}

	/** full constructor */
	public ViewTreeCode(ViewTreeCodeId id) {
		this.id = id;
	}

	// Property accessors

	public ViewTreeCodeId getId() {
		return this.id;
	}

	public void setId(ViewTreeCodeId id) {
		this.id = id;
	}

}